#!/bin/bash
set -uo pipefail

# =============================================================================
# Preflight — external prerequisites
# =============================================================================
# The things that must exist *outside* this repository before a deployment can
# work, and which no script can create for you: a cloud account with quota, an
# authenticated CLI, a domain you control, and DNS delegated to the cloud's DNS
# service so cert-manager can issue certificates.
#
# Checks what it can, asks about what it cannot, and records the answers in
# k8s/scripts/<env>/preflight.ok so quickstart does not ask twice.
#
# Usage:
#   ./preflight.sh --env aws-dev              full check + confirmations
#   ./preflight.sh --env aws-dev --dns        DNS zone and delegation only
#   ./preflight.sh --env aws-dev --recheck    ignore the recorded answers
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/common.sh"

REPO_ROOT="${SCRIPT_DIR}/../.."

ENV=""
DNS_ONLY=false
RECHECK=false
ASSUME_YES=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --env)      ENV="${2:-}"; shift 2 ;;
        --dns)      DNS_ONLY=true; shift ;;
        --recheck)  RECHECK=true; shift ;;
        --yes|-y)   ASSUME_YES=true; shift ;;
        -h|--help)
            echo "Usage: ./devhub preflight --env <environment> [--dns] [--recheck]"
            exit 0
            ;;
        *) log_error "Unknown option: $1"; exit 1 ;;
    esac
done

[[ -n "$ENV" ]] || { log_error "Missing --env"; exit 1; }
if [[ " ${PLATFORM_ENVS} ${WORKLOAD_ENVS} " != *" ${ENV} "* ]]; then
    log_error "Unknown environment: ${ENV}"
    exit 1
fi

CLOUD="$([[ "$ENV" == "local" ]] && echo local || echo "${ENV%%-*}")"
ENV_DIR="${SCRIPT_DIR}/${ENV}"
CONFIG_FILE="${REPO_ROOT}/k8s/overlays/${ENV}/config.yaml"
MARKER="${ENV_DIR}/preflight.ok"
mkdir -p "$ENV_DIR"

DOMAIN="$(yaml_get "$CONFIG_FILE" domain 2>/dev/null || true)"
[[ "$DOMAIN" == *example.com ]] && DOMAIN=""

FAILED=0
WARNED=0
ok()   { printf '  %b✓%b %s\n' "$GREEN" "$NC" "$1"; }
bad()  { printf '  %b✗%b %s\n' "$RED" "$NC" "$1"; FAILED=$((FAILED+1)); }
warn() { printf '  %b!%b %s\n' "$YELLOW" "$NC" "$1"; WARNED=$((WARNED+1)); }
note() { printf '    %s\n' "$1"; }

confirm() {
    local answer
    $ASSUME_YES && return 0
    [[ -t 0 ]] || return 1
    read -r -p "  $1 [y/N]: " answer
    [[ "$answer" =~ ^[Yy] ]]
}

# =============================================================================
# What this platform assumes
# =============================================================================

print_assumptions() {
    cat <<EOF

$(printf '%b' "${CYAN}")────────────────────────────────────────────────────────────────────
  Assumptions for ${ENV}
────────────────────────────────────────────────────────────────────$(printf '%b' "${NC}")
EOF

    if [[ "$ENV" == "local" ]]; then
        cat <<'EOF'

  1. A local Kubernetes cluster is running (Rancher Desktop, k3s, kind, minikube)
     with at least 4 CPU and 8 GB RAM available to it. Prometheus, Loki and
     Keycloak are the hungry ones.

  2. Services are reachable as *.localhost. On Windows, the WSL2 host needs the
     hosts-file entries created by k8s/scripts/windows/setup-hosts.ps1 (run as
     Administrator).

  3. TLS comes from a local CA generated by this repo. Browsers will not trust it
     until you install the CA — k8s/scripts/windows/install-ca.ps1, or add
     k8s/certs/ca/ca.crt to your system trust store.

  4. No cloud account, no public DNS, no Let's Encrypt. Nothing here is reachable
     from outside your machine.

EOF
        return
    fi

    cat <<EOF

  1. A ${CLOUD} account, with a CLI authenticated to it and permission to create
     networks, a Kubernetes cluster, managed databases, object storage and IAM
     identities. Provisioning creates billable resources.

  2. Enough quota for the cluster in your chosen region: typically 3 nodes, one
     load balancer, one NAT gateway, a managed database and a cache.

  3. A registered domain you control. This platform publishes services as
     keycloak.<domain>, git.<domain>, ci.<domain>, argocd.<domain> and so on.

  4. DNS for that domain is hosted in ${CLOUD}'s DNS service, and your registrar's
     nameservers point at it. Two things depend on this:
        - external-dns writes records into that zone automatically
        - cert-manager proves domain ownership to Let's Encrypt over HTTP-01,
          which only works once the records resolve publicly
     You can provision infrastructure before delegation is complete, but
     certificates will stay pending until it is.

  5. An email address for Let's Encrypt expiry notices.

  6. Somewhere to keep tofu state: an object storage bucket (the setup wizard can
     create it) — never local files, since state holds database passwords.

EOF

    case "$CLOUD" in
        aws)
            cat <<'EOF'
  AWS specifics
     - A Route53 public hosted zone for the domain must exist BEFORE `tofu apply`:
       the module looks it up with a data source and the plan fails without it.
     - The Cognito domain prefix must be globally unique across all AWS accounts.
     - S3 bucket names are globally unique; the prefix derives from your env name.

EOF
            ;;
        azure)
            cat <<'EOF'
  Azure specifics
     - An Azure DNS zone for the domain must exist BEFORE `tofu apply` (data
       source lookup, same as above).
     - Creating the Entra ID app registration for Keycloak federation needs
       directory permissions (Application.ReadWrite.All or Application
       Administrator). Without them the azuread resources fail.
     - To disable the AKS local admin account you need the object ids of the
       Entra groups that should hold cluster-admin.

EOF
            ;;
        gcp)
            cat <<'EOF'
  GCP specifics
     - The project must exist with billing enabled; the module enables the APIs
       it needs (container, sqladmin, redis, cloudkms, servicenetworking).
     - A Cloud DNS managed zone for the domain, delegated from your registrar.
     - The Google OAuth client for Keycloak's Google login has no Terraform
       resource — create it by hand and put it in manual-secrets.env.
     - GCS bucket names are globally unique.

EOF
            ;;
        upcloud)
            cat <<'EOF'
  UpCloud specifics
     - UPCLOUD_USERNAME / UPCLOUD_PASSWORD exported, for a subaccount with API
       access enabled.
     - UpCloud has no DNS product and no external-dns provider: DNS is expected
       to be in Cloudflare. You need a Cloudflare zone for the domain and an API
       token with DNS:Edit, stored as the external-dns-cloudflare secret.
     - No private control-plane endpoint exists, so at least one CIDR must be
       allow-listed for the API server.
     - tofu state goes in Managed Object Storage (S3-compatible); create the
       instance and an access key first, and export them as
       AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY.

EOF
            ;;
    esac
}

# =============================================================================
# Automated checks
# =============================================================================

check_tools() {
    echo ""
    echo "Tooling"
    local t
    for t in kubectl helm jq envsubst openssl curl; do
        command -v "$t" &>/dev/null && ok "$t" || bad "$t is not installed"
    done

    [[ "$CLOUD" == "local" ]] && return

    command -v tofu &>/dev/null && ok "tofu" || bad "tofu is not installed"

    case "$CLOUD" in
        aws)     command -v aws     &>/dev/null && ok "aws CLI"    || bad "aws CLI is not installed" ;;
        azure)   command -v az      &>/dev/null && ok "az CLI"     || bad "az CLI is not installed" ;;
        gcp)     command -v gcloud  &>/dev/null && ok "gcloud"     || bad "gcloud is not installed" ;;
        upcloud) command -v upctl   &>/dev/null && ok "upctl"      || warn "upctl not installed (kubeconfig fetch will be manual)" ;;
    esac
}

check_cloud_auth() {
    [[ "$CLOUD" == "local" ]] && return
    echo ""
    echo "Cloud account"

    case "$CLOUD" in
        aws)
            local who
            who="$(aws sts get-caller-identity --query 'Arn' --output text 2>/dev/null)"
            [[ -n "$who" ]] && ok "authenticated as ${who}" || bad "aws CLI is not authenticated (aws configure / SSO login)"
            ;;
        azure)
            local sub
            sub="$(az account show --query 'name' -o tsv 2>/dev/null)"
            [[ -n "$sub" ]] && ok "subscription: ${sub}" || bad "az CLI is not logged in (az login)"
            ;;
        gcp)
            local acct proj
            acct="$(gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null | head -1)"
            proj="$(gcloud config get-value project 2>/dev/null)"
            [[ -n "$acct" ]] && ok "authenticated as ${acct}" || bad "gcloud is not authenticated (gcloud auth login)"
            [[ -n "$proj" && "$proj" != "(unset)" ]] && ok "default project: ${proj}" \
                || warn "no default project set (the setup wizard will ask for one)"
            gcloud auth application-default print-access-token &>/dev/null \
                && ok "application-default credentials present" \
                || warn "no ADC — run: gcloud auth application-default login"
            ;;
        upcloud)
            if [[ -n "${UPCLOUD_USERNAME:-}" && -n "${UPCLOUD_PASSWORD:-}" ]]; then
                ok "UPCLOUD_USERNAME / UPCLOUD_PASSWORD are set"
            else
                bad "UPCLOUD_USERNAME / UPCLOUD_PASSWORD are not exported"
            fi
            [[ -n "${AWS_ACCESS_KEY_ID:-}" ]] && ok "object storage key exported (for tofu state)" \
                || warn "AWS_ACCESS_KEY_ID not set — needed for the S3-compatible state backend"
            ;;
    esac
}

check_local_cluster() {
    [[ "$CLOUD" == "local" ]] || return
    echo ""
    echo "Local cluster"

    if ! kubectl --request-timeout=8s get --raw /readyz &>/dev/null; then
        bad "no reachable Kubernetes cluster (start Rancher Desktop)"
        return
    fi
    ok "cluster reachable: $(kubectl config current-context 2>/dev/null)"

    local cpu mem_ki mem_gi
    cpu="$(kubectl get nodes -o jsonpath='{range .items[*]}{.status.allocatable.cpu}{"\n"}{end}' 2>/dev/null \
           | sed 's/m$//' | awk '{ if ($1 > 100) s += $1/1000; else s += $1 } END { print int(s) }')"
    mem_ki="$(kubectl get nodes -o jsonpath='{range .items[*]}{.status.allocatable.memory}{"\n"}{end}' 2>/dev/null \
              | sed 's/Ki$//' | awk '{s += $1} END {print int(s)}')"
    mem_gi=$(( ${mem_ki:-0} / 1024 / 1024 ))

    [[ "${cpu:-0}" -ge 4 ]] && ok "${cpu} CPU allocatable" \
        || warn "only ${cpu:-0} CPU allocatable — 4+ needed; raise it in Rancher Desktop"
    [[ "$mem_gi" -ge 8 ]] && ok "${mem_gi} GiB memory allocatable" \
        || warn "only ${mem_gi} GiB allocatable — 8+ recommended for the full platform"
}

# DNS: the zone must exist in the cloud's DNS service, and the registrar must
# delegate to it. Both are checkable; neither is fixable from here.
check_dns() {
    [[ "$CLOUD" == "local" ]] && return
    echo ""
    echo "DNS"

    if [[ -z "$DOMAIN" ]]; then
        warn "no domain configured yet — run './devhub setup --env ${ENV}' first"
        note "then re-run: ./devhub preflight --env ${ENV} --dns"
        return
    fi

    ok "domain: ${DOMAIN}"

    local zone_ns=""
    case "$CLOUD" in
        aws)
            if command -v aws &>/dev/null; then
                local zone_id
                zone_id="$(aws route53 list-hosted-zones-by-name --dns-name "${DOMAIN}." \
                    --query "HostedZones[?Name=='${DOMAIN}.'].Id" --output text 2>/dev/null)"
                if [[ -n "$zone_id" && "$zone_id" != "None" ]]; then
                    ok "Route53 public hosted zone exists (${zone_id##*/})"
                    zone_ns="$(aws route53 get-hosted-zone --id "$zone_id" \
                        --query 'DelegationSet.NameServers' --output text 2>/dev/null | tr '\t' '\n')"
                else
                    bad "no Route53 hosted zone for ${DOMAIN}"
                    note "tofu looks this zone up with a data source — the plan fails without it:"
                    note "  aws route53 create-hosted-zone --name ${DOMAIN} --caller-reference \$(date +%s)"
                fi
            fi
            ;;
        azure)
            if command -v az &>/dev/null; then
                local rg
                rg="$(az network dns zone list --query "[?name=='${DOMAIN}'].resourceGroup" -o tsv 2>/dev/null | head -1)"
                if [[ -n "$rg" ]]; then
                    ok "Azure DNS zone exists (resource group: ${rg})"
                    zone_ns="$(az network dns zone show -n "${DOMAIN}" -g "$rg" \
                        --query 'nameServers' -o tsv 2>/dev/null)"
                else
                    bad "no Azure DNS zone for ${DOMAIN}"
                    note "tofu looks this zone up with a data source — the plan fails without it:"
                    note "  az network dns zone create -n ${DOMAIN} -g <resource-group>"
                fi
            fi
            ;;
        gcp)
            if command -v gcloud &>/dev/null; then
                local zone
                zone="$(gcloud dns managed-zones list --filter="dnsName=${DOMAIN}." \
                        --format='value(name)' 2>/dev/null | head -1)"
                if [[ -n "$zone" ]]; then
                    ok "Cloud DNS managed zone exists (${zone})"
                    zone_ns="$(gcloud dns managed-zones describe "$zone" \
                        --format='value(nameServers)' 2>/dev/null | tr ';' '\n' | tr -d ' ')"
                else
                    warn "no Cloud DNS managed zone for ${DOMAIN}"
                    note "external-dns has nowhere to write records until this exists:"
                    note "  gcloud dns managed-zones create devhub --dns-name=${DOMAIN}. --description=devhub"
                fi
            fi
            ;;
        upcloud)
            warn "UpCloud has no DNS product — this platform expects Cloudflare"
            note "Create the zone in Cloudflare, delegate to it, then create the token secret:"
            note "  kubectl create secret generic external-dns-cloudflare -n external-dns \\"
            note "    --from-literal=api-token=<token with DNS:Edit>"
            ;;
    esac

    # Delegation: does the public internet agree the zone is authoritative?
    if command -v dig &>/dev/null; then
        local live_ns
        live_ns="$(dig +short NS "${DOMAIN}" 2>/dev/null | sed 's/\.$//' | sort)"
        if [[ -z "$live_ns" ]]; then
            warn "no public NS records for ${DOMAIN} yet — delegation is incomplete"
            note "Certificates stay pending until the registrar points at the zone's nameservers."
        elif [[ -n "$zone_ns" ]]; then
            local first
            first="$(echo "$zone_ns" | head -1 | sed 's/\.$//')"
            if echo "$live_ns" | grep -qi "$first"; then
                ok "delegation looks correct ($(echo "$live_ns" | head -1))"
            else
                warn "public NS records do not match the cloud zone"
                note "public:  $(echo "$live_ns" | tr '\n' ' ')"
                note "zone:    $(echo "$zone_ns" | tr '\n' ' ')"
                note "Update the nameservers at your registrar; propagation can take hours."
            fi
        else
            ok "public NS records exist ($(echo "$live_ns" | head -1))"
        fi
    else
        warn "dig not installed — cannot verify registrar delegation"
    fi
}

# Things no command can determine.
ask_confirmations() {
    [[ "$CLOUD" == "local" ]] && return 0
    echo ""
    echo "Confirmations"

    local q=(
        "Do you control the domain at its registrar (able to change nameservers)?"
        "Is billing enabled on this ${CLOUD} account, and are you happy to create billable resources?"
    )
    case "$CLOUD" in
        azure) q+=("Do you have Entra directory permissions to create app registrations?") ;;
        gcp)   q+=("Is the target project created with billing enabled?") ;;
    esac

    local item
    for item in "${q[@]}"; do
        if confirm "$item"; then
            ok "confirmed"
        else
            bad "not confirmed: ${item}"
        fi
    done
}

write_marker() {
    {
        echo "# Preflight confirmed for ${ENV}"
        echo "# Re-check with: ./devhub preflight --env ${ENV} --recheck"
        echo "env=${ENV}"
        echo "cloud=${CLOUD}"
        echo "domain=${DOMAIN:-<unset>}"
        echo "warnings=${WARNED}"
    } > "$MARKER"
    chmod 600 "$MARKER"
}

# =============================================================================
# Main
# =============================================================================

if $DNS_ONLY; then
    check_dns
    echo ""
    [[ $FAILED -eq 0 ]] && { log_info "DNS checks passed"; exit 0; }
    log_error "DNS is not ready — see above"
    exit 1
fi

if [[ -f "$MARKER" ]] && ! $RECHECK; then
    log_info "Preflight already confirmed for ${ENV} ($(grep '^domain=' "$MARKER" | cut -d= -f2))"
    log_info "Re-run with --recheck to go through it again"
    exit 0
fi

print_assumptions
check_tools
check_cloud_auth
check_local_cluster
check_dns
ask_confirmations

echo ""
if [[ $FAILED -gt 0 ]]; then
    log_error "${FAILED} prerequisite(s) not met — fix the ✗ items above and re-run"
    log_error "  ./devhub preflight --env ${ENV}"
    exit 1
fi

if [[ $WARNED -gt 0 ]]; then
    log_warn "${WARNED} warning(s). These do not block provisioning, but DNS-related"
    log_warn "warnings mean certificates will stay pending until they are resolved."
    confirm "Continue anyway?" || { log_warn "Stopped — nothing recorded"; exit 1; }
fi

write_marker
log_info "Prerequisites confirmed for ${ENV}"
echo ""
if [[ "$ENV" == "local" ]]; then
    # local has no infrastructure layer and nothing for the setup wizard to write.
    echo "  Next: ./devhub quickstart --env local   (or ./devhub bootstrap --env local)"
else
    echo "  Next: ./devhub setup --env ${ENV}"
fi
echo ""
