#!/bin/bash
set -euo pipefail

# =============================================================================
# End-to-end validation of a deployed environment
# =============================================================================
# validate-overlays.sh answers "would this deploy?". This answers "does the
# thing that was deployed work?" — from a browser, through the gateway, with a
# real Keycloak sign-in, asserting on what each service returns rather than on
# whether its pod is Running.
#
# The gap it closes is the class of failure where every pod is healthy and the
# platform is unusable: a Keycloak realm that no longer exists, a Helm value
# still containing the literal ${DOMAIN}, an ArgoCD that cannot read its
# repository, a sealed Vault, a Loki nobody can query.
#
# Read-only. Nothing here creates a repository, triggers a pipeline or writes a
# secret, so it is safe to point at a production environment.
#
# Usage: ./validate-e2e.sh --env <env> [-- <playwright args>]
#   --env <env>       environment to test (required)
#   --headed          watch it run in a browser window
#   --grep <pattern>  only tests matching (e.g. --grep grafana)
#   --report          open the HTML report when finished
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/common.sh"

E2E_DIR="${SCRIPT_DIR}/../e2e"

for arg in "$@"; do
    if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
        sed -n '5,26p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
        exit 0
    fi
done

parse_env_arg "$@"

HEADED=false
OPEN_REPORT=false
PW_ARGS=()

set -- "${ARGS[@]+"${ARGS[@]}"}"
while [[ $# -gt 0 ]]; do
    case "$1" in
        --headed) HEADED=true; shift ;;
        --report) OPEN_REPORT=true; shift ;;
        --grep)   PW_ARGS+=(--grep "$2"); shift 2 ;;
        --) shift; PW_ARGS+=("$@"); break ;;
        *)  PW_ARGS+=("$1"); shift ;;
    esac
done

setup_paths
parse_config

if [[ ! -d "$E2E_DIR" ]]; then
    log_error "No e2e suite at ${E2E_DIR}"
    exit 1
fi

log_phase "End-to-end validation of ${ENV}"

# ── What the suite needs to sign in ──────────────────────────────────
#
# The realm password is generated by setup-keycloak.sh and lives only in the
# gitignored env directory. No password, no run: a suite that silently degrades
# to anonymous checks would report a broken platform as fine.
OIDC_SECRETS="${SCRIPT_ENV_DIR}/oidc-secrets.env"
if [[ ! -f "$OIDC_SECRETS" ]]; then
    log_error "No ${OIDC_SECRETS}"
    log_error "Keycloak has not been set up for ${ENV}: ./devhub keycloak --env ${ENV}"
    exit 1
fi
# shellcheck disable=SC1090
source "$OIDC_SECRETS"

if [[ -z "${PLATFORM_ADMIN_PASSWORD:-}" ]]; then
    log_error "PLATFORM_ADMIN_PASSWORD is missing from ${OIDC_SECRETS}"
    exit 1
fi

if [[ -z "${DOMAIN:-}" ]]; then
    log_error "domain is not set in ${OVERLAY_DIR}/config.yaml"
    exit 1
fi

log_info "Domain: ${DOMAIN}"
log_info "Signing in as: platform-admin (realm devops)"

# ── Does this workstation resolve the platform's hostnames? ──────────
#
# Reported, not enforced. The suite drives every request from inside Chromium,
# which resolves *.localhost to loopback itself (RFC 6761) — as curl does, and
# as glibc does not. So a local run works with an out-of-date hosts file, but
# the person reading the result still needs to know their own browser will not
# reach these URLs.
UNRESOLVED=()
for sub in keycloak vault git ci argocd grafana prometheus headlamp home; do
    getent hosts "${sub}.${DOMAIN}" >/dev/null 2>&1 || UNRESOLVED+=("${sub}.${DOMAIN}")
done

if [[ ${#UNRESOLVED[@]} -gt 0 ]]; then
    log_warn "Not resolvable from this machine (the suite still tests them — Chromium"
    log_warn "resolves *.localhost on its own — but your browser will not open them):"
    for name in "${UNRESOLVED[@]}"; do log_warn "  ${name}"; done
    if [[ "$ENV" == "local" ]]; then
        log_warn "Fix once in an Administrator PowerShell, from the repository root:"
        log_warn "  cd k8s\\scripts\\windows; .\\setup-hosts.ps1"
    else
        log_warn "Check external-dns has published the records: ./devhub status --env ${ENV}"
    fi
fi

# ── Tooling ──────────────────────────────────────────────────────────
if ! command -v node >/dev/null 2>&1; then
    log_error "node is required (https://nodejs.org). The suite is Playwright."
    exit 1
fi

if [[ ! -d "${E2E_DIR}/node_modules" ]]; then
    log_step "Installing the test runner (once)..."
    (cd "$E2E_DIR" && npm install --silent) || {
        log_error "npm install failed in ${E2E_DIR}"
        exit 1
    }
fi

# Browsers land in ~/.cache/ms-playwright and are shared with any other
# Playwright install on the machine, so this is usually a no-op.
if ! (cd "$E2E_DIR" && npx --no-install playwright install chromium >/dev/null 2>&1); then
    log_warn "Could not verify the Chromium download — continuing"
fi

# ── Run ──────────────────────────────────────────────────────────────
export DEVHUB_ENV="$ENV"
export DEVHUB_DOMAIN="$DOMAIN"
export DEVHUB_ADMIN_USER="platform-admin"
export DEVHUB_ADMIN_PASSWORD="$PLATFORM_ADMIN_PASSWORD"
export DEVHUB_GITOPS_REPO_URL="${GITOPS_REPO_URL:-}"

# Headlamp authenticates at the gateway, then asks for a ServiceAccount token to
# reach the API — the same token `./deploy.sh --env <env> headlamp-token` prints.
# Handing it to the suite is what lets the Headlamp spec assert that the curated
# read-only RBAC actually works, instead of stopping at the token screen.
export DEVHUB_HEADLAMP_TOKEN="$(kubectl get secret headlamp-view-token -n headlamp \
    -o jsonpath='{.data.token}' 2>/dev/null | base64 -d || true)"

$HEADED && PW_ARGS+=(--headed)

log_step "Running the suite..."
set +e
(cd "$E2E_DIR" && npx --no-install playwright test "${PW_ARGS[@]+"${PW_ARGS[@]}"}")
STATUS=$?
set -e

echo ""
if [[ $STATUS -eq 0 ]]; then
    log_info "${ENV} is working end-to-end"
else
    log_error "End-to-end validation failed for ${ENV}"
    log_error "Details, screenshots and traces:"
    log_error "  ${E2E_DIR}/report/index.html"
    log_error "Open it with: cd k8s/e2e && npx playwright show-report report"
fi

if $OPEN_REPORT; then
    (cd "$E2E_DIR" && npx --no-install playwright show-report report) || true
fi

exit $STATUS
