# Monitoring GCP overlay values
# Merged with base/devops/monitoring/prometheus-stack-values.yaml

grafana:

  grafana.ini:
    server:
      root_url: https://grafana.${DOMAIN}
    auth.generic_oauth:
      auth_url: https://keycloak.${DOMAIN}/realms/devops/protocol/openid-connect/auth
      token_url: http://keycloak-service.keycloak.svc.cluster.local:8080/realms/devops/protocol/openid-connect/token
      api_url: http://keycloak-service.keycloak.svc.cluster.local:8080/realms/devops/protocol/openid-connect/userinfo

  envValueFrom:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
      secretKeyRef:
        name: grafana-oidc-secret
        key: client-secret
