# cert-manager Helm values
# Chart: jetstack/cert-manager
# Docs: https://cert-manager.io/docs/

installCRDs: true

replicaCount: 2

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

webhook:
  replicaCount: 2
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

cainjector:
  replicaCount: 2
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Prometheus metrics
prometheus:
  enabled: true
  servicemonitor:
    enabled: true
