apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tshub

resources:
  - namespace.yaml

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/part-of: tshub
  app.kubernetes.io/managed-by: kustomize
